from pydantic import BaseModel, Field

class InferenceRequest(BaseModel):
    model: str = Field(..., description="The identifier of the model to use for inference (e.g., 'meta-llama/Llama-3.1-8B-Instruct').", min_length=1)
    prompt: str = Field(..., description="The input prompt text to send to the model.", min_length=1)

class InferenceResponse(BaseModel):
    generated_text: str = Field(..., description="The text generated by the AI model.")