from pydantic import BaseModel, Field
from typing import List
from backend.core.enums.field_type_enum import FieldType

class SuggestedDocumentField(BaseModel):
    name: str = Field(
        ...,
        description="The display name of the field (e.g., 'Contracting Company', 'Service Value', 'Start Date'). Used as a label in the form.",
        min_length=1
    )
    type: FieldType = Field(
        ...,
        description="The type of the field, using the FieldType Enum (e.g., text, integer, decimal, textarea, select, radio, checkbox, date, email)."
    )
    required: bool = Field(
        False,
        description="Whether the field is mandatory (True) or optional (False). Defaults to False."
    )
    description: str = Field(
        ...,
        description="A brief description explaining the purpose or expected content of the field.",
        min_length=1
    )

    def __post_init__(self):
        self.name = self.name.strip()
        self.description = self.description.strip()

class GenerateDocumentFieldsRequest(BaseModel):
    document_type_name: str = Field(
        ...,
        description="The name of the document type for which to suggest fields (e.g., 'Service Contract').",
        min_length=1
    )
    document_type_description: str = Field(
        ...,
        description="A brief description of the document type, providing context for field generation.",
        min_length=1
    )

    def __post_init__(self):
        self.document_type_name = self.document_type_name.strip()
        self.document_type_description = self.document_type_description.strip()


class GenerateDocumentFieldsResponse(BaseModel):
    document_type: str = Field(
        ...,
        description="The name of the document type for which the fields were suggested.",
        min_length=1
    )
    description: str = Field(
        ...,
        description="The description of the document type provided as input or generated by the AI.",
        min_length=1
    )
    fields: List[SuggestedDocumentField] = Field(
        ...,
        description="The list of fields suggested for the document type."
    )

    def __post_init__(self):
        self.document_type = self.document_type.strip()
        self.description = self.description.strip()